describe('Login Scenario', () => {
  it('Success Login', () => {
    // cy.intercept('**').as('requests')
    cy.visit('https://www.saucedemo.com/')
    // cy.get('#user-name').type('standard_user')
    cy.get('#user-name').type('standard_user')
    cy.get('[data-test="password"]').type('secret_sauce')
    cy.get('[data-test="login-button"]').click()
    cy.get('.app_logo').should('be.visible')
    cy.get('.title').should('be.visible')
    cy.url().should('eq', 'https://www.saucedemo.com/inventory.html')
  })
  it('Failed Login - wrong credential', () => {
    // cy.intercept('**').as('requests')
    cy.visit('https://www.saucedemo.com/')
    // cy.get('#user-name').type('ngawur_user')
    cy.get('#user-name').type('ngawur_user')
    cy.get('[data-test="password"]').type('ngawurpass')
    cy.get('[data-test="login-button"]').click()
    cy.get('[data-test="error"]').should('be.visible')
    cy.get('[data-test="error"]').should('contain.text', 'Epic sadface: Username and password')
  })
  it('Failed Login - Locked User', () => {
    // cy.intercept('**').as('requests')
    cy.visit('https://www.saucedemo.com/')
    // cy.get('#user-name').type('ngawur_user')
    cy.get('#user-name').type('locked_out_user')
    cy.get('[data-test="password"]').type('secret_sauce')
    cy.get('[data-test="login-button"]').click()
    cy.get('[data-test="error"]').should('be.visible')
    cy.get('[data-test="error"]').should('contain.text', 'Epic sadface: Sorry, this user has been locked out')
  })
  it('Add to Cart', () => {
    // cy.intercept('**').as('requests')
    cy.visit('https://www.saucedemo.com/')
    // cy.get('#user-name').type('standard_user')
    cy.get('#user-name').type('standard_user')
    cy.get('[data-test="password"]').type('secret_sauce')
    cy.get('[data-test="login-button"]').click()
    cy.get('.app_logo').should('be.visible')
    cy.get('.title').should('be.visible')
    cy.url().should('eq', 'https://www.saucedemo.com/inventory.html')
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('contain.text', 'Add to cart')
  })
  it('See Cart', () => {
    // cy.intercept('**').as('requests')
    cy.visit('https://www.saucedemo.com/')
    // cy.get('#user-name').type('standard_user')
    cy.get('#user-name').type('standard_user')
    cy.get('[data-test="password"]').type('secret_sauce')
    cy.get('[data-test="login-button"]').click()
    cy.get('.app_logo').should('be.visible')
    cy.get('.title').should('be.visible')
    cy.url().should('eq', 'https://www.saucedemo.com/inventory.html')
    cy.get('.shopping_cart_link').should('be.visible')
  })
  it('See Product', () => {
    // cy.intercept('**').as('requests')
    cy.visit('https://www.saucedemo.com/')
    // cy.get('#user-name').type('standard_user')
    cy.get('#user-name').type('standard_user')
    cy.get('[data-test="password"]').type('secret_sauce')
    cy.get('[data-test="login-button"]').click()
    cy.get('.app_logo').should('be.visible')
    cy.get('.title').should('be.visible')
    cy.url().should('eq', 'https://www.saucedemo.com/inventory.html')
    cy.get('.title').should('be.visible')
  })
})