describe('Home Scenario', () => {
  it('See home', () => {
    // cy.intercept('**').as('requests')
    cy.visit('https://www.demoblaze.com/')
    cy.get('.active > .nav-link').should('be.visible')
    cy.get('#cat').should('be.visible')
    cy.get('.active > .d-block').should('be.visible')
    cy.get('.carousel-control-next-icon').should('be.visible')
    cy.contains("Phones").click()
    cy.contains("Samsung galaxy s6").click()
    cy.contains("Add to cart").click()
    cy.contains("Home").click()
    cy.contains("Laptops").click()
    cy.contains('Sony vaio i5').click()
    cy.contains("Add to cart").click()
    cy.contains("Home").click()
    cy.contains("Monitors").click()
    cy.contains('Apple monitor 24').click()
    cy.contains("Add to cart").click()
  })
})